services:
  - type: web
    name: investment-platform-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .
    
  - type: pserv
    name: investment-platform-db
    plan: free
    env: postgres
    envVars:
      - key: POSTGRES_DB
        value: investment_platform
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
